name: Docker Action to test api and push docker image to docker hub 

on:
  push:
    branches: [ action-test ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pwd
          ls -l
          python -m pip install --upgrade pip
          pip install -r auth_api/python/requirements.txt -v 
        
      - name: Test 
        run: |
          python auth_api/python/tests.py
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
        
      - name: Build and push image 
        id: docker_build
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dummy-workflow:latest 
          context: ./auth-api/ #/home/runner/work/sre-bootcamp/sre-bootcamp/auth-api/python
          file: ./auth-api/Dockerfile
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

