name: Docker Action to test api and push docker image to docker hub 

on:
  push:
    branches: [ main ]

jobs:
  sre-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pwd
          ls -l
          python -m pip install --upgrade pip
          pip install -r ./../../auth_api/python/requirements.txt 
        
      - name: Test 
        run: |
          python ./../../auth_api/python/tests.py
